# Generated by Django 3.1.3 on 2020-11-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.SlugField(blank=True, max_length=85),
        ),
    ]
