# Generated by Django 3.1.3 on 2020-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_tipo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
